version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server.prod
    image: syllogy
    container_name: syllogy
    command: node build/index.js
    ports:
      - 3301:5000
    depends_on:
      - db
    links:
      - db
  db:
    image: syllogy:latest
    container_name: syllogy
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=syllogy
    ports:
      - 3102:5432
    volumes:
      - syllogy-db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: gallery-data